# a class describing a round of poker
# initiates a new deck
# players and their chips are taking into account as parameters
# pot starts at 0, or however much the ante
# blinds are set
# players are dealt cards
# players see their cards, and betting begins
# end of betting, flop is dealt
# betting begins
# end of betting, turn is dealt
# betting begins
# end of betting, river is dealt
# betting begins
# end of betting, winner is determined (either by showdown or by all but one player folding)
import cardDeck
import Player

class Round:

    round : int
    deck : list # generated by cardDeck.deck()
    shown_cards : list # cards that have been dealt to the table
    players : list # list of Player objects with their attr
    pot : int
    ante : int
    small_blind : int
    big_blind : int
    dealer : int # index of the dealer in the players list

    def __init__(self, dealer, players, round=0,  ante=0, small_blind=1, big_blind=2):
        self.round = round
        self.deck = cardDeck.deck()
        self.players = players
        self.pot = 0
        self.ante = ante
        self.small_blind = small_blind
        self.big_blind = big_blind
        self.dealer = dealer
    
    def deal_hands(self):
        for i in self.players:
            i.c1 = self.deck.pop()
        for i in self.players:
            i.c2 = self.deck.pop()
    
    def deal_flop(self):
        for i in range(3):
            self.shown_cards.append(self.deck.pop())
    
    def deal_turn(self):
        self.shown_cards.append(self.deck.pop())
    
    def deal_river(self):
        self.shown_cards.append(self.deck.pop())

    """When there is more than 1 player left,
    the winner is determined by the best hand."""
    def calculate_winner(self):
        pass